on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * SUN"

name: check-link-rot

jobs:
  check-link-rot:
    uses: IndrajeetPatil/workflows/.github/workflows/check-link-rot.yaml@main
